insert into public.collections (
  slug,
  number,
  title,
  display_title,
  tagline,
  mood,
  logo,
  logo_sheet,
  bg_class,
  text_class,
  font_class,
  sort_order
) values
  ('thread-classics', '01', 'Thread Classics', 'Thread Classics', 'The Foundation Pieces', 'Refined heritage basics for students who want quiet quality.', 1, 1, 'bg-woven-bg', 'text-woven-text', 'font-display', 1),
  ('minimal-edit', '02', 'Minimal Edit', 'minimal edit', 'Less. Meant.', 'Japanese-inspired cuts, muted tones, and considered whitespace.', 5, 1, 'bg-woven-surface', 'text-woven-text', 'font-syne', 2),
  ('digital-weave', '03', 'Digital Weave', 'DIGITAL WEAVE', 'Generated. Designed. Worn.', 'Pixelated, technical, and built for late-night labs.', 3, 1, 'bg-woven-dark', 'text-woven-inverse', 'font-grotesk', 3),
  ('street-stitch', '04', 'Street Stitch', 'STREET STITCH', 'Built Different.', 'Raw, oversized, noisy, and tuned to campus subculture.', 9, 1, 'bg-woven-bg', 'text-woven-text', 'font-bebas', 4),
  ('glitch-drop', '05', 'Glitch Drop', 'GLITCH DROP', 'Think. Create. Wear.', 'Limited digital distortion with a real countdown pulse.', 6, 1, 'bg-woven-near-black', 'text-woven-inverse', 'font-rajdhani', 5),
  ('society', '06', 'Society Collection', 'Society Collection', 'Est. 2025. For Those Who Lead.', 'Academic heritage for debate nights, MUN floors, and formal campus rituals.', 7, 1, 'bg-woven-tan', 'text-woven-text', 'font-playfair', 6)
on conflict (slug) do update set
  number = excluded.number,
  title = excluded.title,
  display_title = excluded.display_title,
  tagline = excluded.tagline,
  mood = excluded.mood,
  logo = excluded.logo,
  logo_sheet = excluded.logo_sheet,
  bg_class = excluded.bg_class,
  text_class = excluded.text_class,
  font_class = excluded.font_class,
  sort_order = excluded.sort_order;


insert into public.products (
  sku,
  slug,
  name,
  price_pkr,
  collection_slug,
  sizes,
  palette,
  status,
  description,
  material,
  sort_order
) values
  (
    'TC-01',
    'foundation-oxford-shirt',
    'Foundation Oxford Shirt',
    4800,
    'thread-classics',
    array['XS','S','M','L','XL'],
    'from-stone-100 via-neutral-200 to-stone-300',
    'New',
    'A brushed cotton oxford with a relaxed campus fit, soft collar, and stitched Woven mark at the cuff.',
    '220gsm cotton oxford, corozo buttons, reinforced seams.',
    1
  ),
  (
    'TC-02',
    'library-knit-polo',
    'Library Knit Polo',
    5200,
    'thread-classics',
    array['S','M','L','XL'],
    'from-zinc-200 via-stone-100 to-zinc-300',
    null,
    'Fine rib texture, structured placket, and a weight that works from morning lectures to evening critiques.',
    'Cotton viscose knit with ribbed cuffs and collar.',
    2
  ),
  (
    'ME-01',
    'folded-seam-jacket',
    'Folded Seam Jacket',
    7900,
    'minimal-edit',
    array['XS','S','M','L'],
    'from-neutral-300 via-stone-200 to-zinc-100',
    'New',
    'A quiet overshirt with hidden pockets, flat-felled seams, and a sharp box silhouette.',
    'Midweight cotton twill with recycled poly lining.',
    1
  ),
  (
    'ME-02',
    'paperweight-trouser',
    'Paperweight Trouser',
    5600,
    'minimal-edit',
    array['S','M','L','XL'],
    'from-stone-200 via-neutral-100 to-stone-300',
    null,
    'Pleated, cropped, and easy to move in, made for studio days and pinned-up deadlines.',
    'Cotton poplin blend with a matte hand feel.',
    2
  ),
  (
    'DW-01',
    'compile-hoodie',
    'Compile Hoodie',
    6400,
    'digital-weave',
    array['S','M','L','XL'],
    'from-neutral-900 via-cyan-950 to-zinc-800',
    'New',
    'Heavy fleece hoodie with pixel-grid sleeve panels and a hidden headphone loop inside the hood.',
    '320gsm brushed fleece, rib inserts, reflective woven label.',
    1
  ),
  (
    'DW-02',
    'runtime-cargo',
    'Runtime Cargo',
    6900,
    'digital-weave',
    array['S','M','L'],
    'from-zinc-900 via-neutral-700 to-cyan-950',
    null,
    'Tapered cargo pant with utility pockets and tonal grid embroidery at the knee.',
    'Ripstop cotton nylon with matte hardware.',
    2
  ),
  (
    'SS-01',
    'underpass-tee',
    'Underpass Tee',
    3200,
    'street-stitch',
    array['S','M','L','XL'],
    'from-neutral-950 via-stone-700 to-neutral-200',
    'New',
    'Oversized tee with cracked ink typography, raw edge label, and a heavy drape.',
    '240gsm cotton jersey with discharge print.',
    1
  ),
  (
    'SS-02',
    'zine-canvas-vest',
    'Zine Canvas Vest',
    6100,
    'street-stitch',
    array['S','M','L'],
    'from-stone-800 via-neutral-500 to-stone-200',
    null,
    'Canvas vest with asymmetric pockets and removable hand-tag panel for pins and patches.',
    'Washed canvas, cotton tape, antique nickel snaps.',
    2
  ),
  (
    'GD-01',
    'signal-loss-shell',
    'Signal Loss Shell',
    8400,
    'glitch-drop',
    array['S','M','L'],
    'from-fuchsia-950 via-neutral-950 to-cyan-950',
    'Notify Me',
    'Limited shell jacket with sliced reflective panels and a packable hood. Next drop opens soon.',
    'Water-resistant nylon, mesh lining, reflective heat transfer.',
    1
  ),
  (
    'GD-02',
    'ghost-frame-tee',
    'Ghost Frame Tee',
    3600,
    'glitch-drop',
    array['S','M','L','XL'],
    'from-neutral-950 via-fuchsia-900 to-cyan-900',
    'Sold Out',
    'A graphic tee with offset cyan and magenta frame graphics, released in a numbered run.',
    'Cotton jersey with soft-hand screen print.',
    2
  ),
  (
    'SC-01',
    'debate-club-blazer',
    'Debate Club Blazer',
    12800,
    'society',
    array['XS','S','M','L'],
    'from-amber-950 via-stone-700 to-woven-tan',
    'New',
    'Unstructured blazer with crest lining, soft shoulders, and a lapel made for society nights.',
    'Cotton wool blend with satin jacquard lining.',
    1
  ),
  (
    'SC-02',
    'chairperson-waistcoat',
    'Chairperson Waistcoat',
    7300,
    'society',
    array['S','M','L','XL'],
    'from-stone-700 via-woven-tan to-amber-100',
    null,
    'A tailored waistcoat with double-rule stitching and a neat inner pocket for debate notes.',
    'Textured cotton blend, horn buttons, contrast piping.',
    2
  )
on conflict (slug) do update set
  sku = excluded.sku,
  name = excluded.name,
  price_pkr = excluded.price_pkr,
  collection_slug = excluded.collection_slug,
  sizes = excluded.sizes,
  palette = excluded.palette,
  status = excluded.status,
  description = excluded.description,
  material = excluded.material,
  sort_order = excluded.sort_order;